# Generated by Django 4.1 on 2024-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0002_rename_nameco_tbl_company_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
