# Generated by Django 4.1 on 2024-01-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0003_tbl_company_password_tbl_company_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='companyaddress_city',
        ),
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='companyemail',
        ),
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='websitelink',
        ),
        migrations.AddField(
            model_name='tbl_jobpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portalapp.tbl_category'),
        ),
        migrations.AddField(
            model_name='tbl_jobpost',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portalapp.tbl_company'),
        ),
    ]
