# Generated by Django 4.1.5 on 2024-02-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0006_tbl_mock_tbl_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=20, null=True)),
                ('choice2', models.CharField(max_length=20, null=True)),
                ('choice3', models.CharField(max_length=20, null=True)),
                ('choice4', models.CharField(max_length=20, null=True)),
                ('qns_ans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portalapp.tbl_questionanswer')),
            ],
        ),
    ]
