# Generated by Django 4.1.5 on 2024-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0007_tbl_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_questionanswer',
            name='choice1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_questionanswer',
            name='choice2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_questionanswer',
            name='choice3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_questionanswer',
            name='choice4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_questionanswer',
            name='mark',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
