# Generated by Django 4.1.5 on 2024-02-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0009_remove_tbl_choice_qns_ans_delete_tbl_company_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='beginner',
        ),
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='skills',
        ),
        migrations.CreateModel(
            name='tbl_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portalapp.tbl_jobpost')),
            ],
        ),
    ]
