# Generated by Django 4.1.5 on 2024-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0010_remove_tbl_jobpost_advanced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_jobpost',
            name='hiringtimeline',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
