# Generated by Django 4.1.5 on 2024-02-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0013_tbl_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_jobapplication',
            name='cover_letter',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='tbl_Mock_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('total_mark', models.IntegerField(null=True)),
                ('Result', models.CharField(max_length=20, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portalapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Mock_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('selected_answer', models.TextField(null=True)),
                ('Correct_answer', models.CharField(max_length=20, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('mock_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portalapp.tbl_mock_user')),
            ],
        ),
    ]
