# Generated by Django 4.1.5 on 2024-02-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0014_alter_tbl_jobapplication_cover_letter_tbl_mock_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mock_answers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portalapp.tbl_register'),
        ),
    ]
