# Generated by Django 4.1.5 on 2024-02-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portalapp', '0015_tbl_mock_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_jobapplication',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portalapp.tbl_jobpost'),
        ),
    ]
